apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-statefulset
spec:
  serviceName: "my-service"   # required, even if you haven't defined it yet
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: web-2048
        image: web-2048
        imagePullPolicy: Never
        ports:
        - containerPort: 80
