==== AIOps

AI for IT operations. For example natural language processing and machine learning models to automate and optimize IT service management and operational workflows.
Examples: Ingests volumes of data generated by IT components (which are ever-increasing). Diagnoses root causes and sends it to IT.

==== AIOps versions

Domain-centric: AIOps vendors are focused on bringing AI-driven decisions to a certain domain – 
typically in the monitoring spaces – like Application Monitoring, Infrastructure Monitoring, Network monitoring, etc.

Domain-agnostic: AIOps vendors are generally focused on cross-domain IT data, bringing data from ITOM, ITSM, CMDB/ITAM tools and 
providing aggregate intelligence, cross-domain correlation, bringing context to data, and driving broader autonomous decisions at scale.

==== What it's not

MLOps != AIOps 

MLOps: Continous delivery of ML models into productions. 

AIOps is a way to automate the system with the help of ML and Big Data.

MLOps is a way to standardize the process of deploying ML systems and filling the gaps between teams, to give all project stakeholders more clarity.

==== Kubernetes AIOps tools, 10 examples, description, KPI

.1. k8sgpt: 
* A tool for scanning your Kubernetes clusters, diagnosing, and triaging issues in simple English.
* https://github.com/k8sgpt-ai/k8sgpt
* Installs (365 days): 5,761 | Stars on Github: 7100

.2. kagent:
* A Kubernetes native framework for building AI agents. It makes it easy to build, deploy and manage AI agents in Kubernetes.
* https://github.com/kagent-dev/kagent
* Installs (365 days): 48 | Stars on Github: 1800

.3. kubectl-ai:
* Acts as an intelligent interface, translating user intent into precise Kubernetes operations, making Kubernetes management more accessible and efficient.
* https://github.com/GoogleCloudPlatform/kubectl-ai
* Installs (365 days): 1,474 | Stars on Github: 7000

.4. kube-copilot:
* Kubernetes Copilot powered by LLM, which leverages advanced language models to streamline and enhance Kubernetes cluster management.
* https://github.com/feiskyer/kube-copilot
* Stars on Github: 225

.5. karpor:
* Karpor is Intelligence for Kubernetes. It brings advanced Search, Insight and AI to Kubernetes. It is essentially a Kubernetes Visualization Tool. 
* https://github.com/KusionStack/karpor
* Stars on Github: 1600

.6. kubebuddy:
* An AI-powered Kubernetes dashboard tool designed to provide a comprehensive and user-friendly interface for managing Kubernetes clusters.
* https://github.com/kubebuddy/kubebuddy
* Stars on Github: 22

.7. krs (Kubetools Recommender System):
* A GenAI-powered Kubetools Recommender system for your Kubernetes cluster.
* https://github.com/kubetoolsca/krs
* Stars on Github: 185

.8. botkube:
* A troubleshooting and monitoring solution that empowers DevOps teams to work more efficiently, enables developers to troubleshoot their applications without special Kubernetes access or knowledge, and improves reliability by delivering timely, context-enhanced notifications about events in your Kubernetes environments.
* https://github.com/kubeshop/botkube
* Stars on Github: 2300

.9. MCP Server for the Kubernetes Ecosystem:
* Model Context Protocol (MCP) server for Kubernetes and OpenShift.
* https://github.com/containers/kubernetes-mcp-server
* Stars on Github: 797

.10. robusta:
* Better Prometheus alerts for Kubernetes - smart grouping, AI enrichment, and automatic remediation.
* https://github.com/robusta-dev/robusta
* Stars on Github: 2900

Install data from: https://formulae.brew.sh/

.generating pdf:
[source,bash]
----
docker pull asciidoctor/docker-asciidoctor
docker run --rm -v $(pwd):/documents/ asciidoctor/docker-asciidoctor asciidoctor-pdf demo.adoc
----

sources:

https://www.ibm.com/think/topics/aiops

https://neptune.ai/blog/mlops-vs-aiops-differences

https://fabrix.ai/blog/what-is-aiops-types-of-aiops/

https://www.linkedin.com/posts/mongkol-thongkraikaew_kubernetes-aiops-devops-activity-7337709784772526080-IKy_/

https://gist.github.com/powerman/d56b2675dfed38deb298

https://stackoverflow.com/questions/50477523/how-to-convert-asciidoc-to-pdf